### ISSUE TITLE
quick question about the relationship between gtk themes and shell themes

### ISSUE THREAD

**Issue by jcklpe** [marinos-m/deepin-bloody-osx-gtk#1]
This is only a gtk theme, correct? but when I look in gnome tweaker it shows this theme as an option, though it doesn't really look anything like the GTK theme. Do you know how or why it's displaying that option?

**Comment by marinos-m** [comment]
It is only a gtk theme yes. In any given theme's folder there's a folder called gnome-shell which contains the css for the shell them - if there's one. The reason you get it as an option in gnome-tweaks is because I forgot to remove the default deepin shell theme folder from the variation with the default window buttons on opendesktop.org as I realised just now. I will reupload the version without the shell theme as soon as possible. Thanks for pointing it out.
